language: node_js
node_js:
  - "8.2.1"

notifications:
  email:
    recipients:
      - anthonyklinga@gmail.com
    on_success: always # default: change
on_failure: always # default: always

install:
  - npm install newman
  - npm install lodash
  - npm install moment

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version

script:
  - newman run tests/Mercado.postman_collection.json -e tests/Mercado.postman_environment.json